-- Semente da taxonomia (Fase 2). Deve permanecer identica a
-- src/lib/taxonomiaSeed.ts — qualquer termo/sinonimo novo aprendido em
-- producao entra via taxonomia_sugestoes -> aprovacao, nunca editando este
-- arquivo depois do deploy inicial.

insert into public.taxonomia_termos (termo, categoria, tipo) values
  ('gerador', 'Gerador / nobreak', 'equipamento'),
  ('ar condicionado', 'Ar condicionado / climatizacao', 'equipamento'),
  ('elevador', 'Elevadores / escadas rolantes', 'equipamento'),
  ('escada rolante', 'Elevadores / escadas rolantes', 'equipamento'),
  ('subestacao', 'Subestacao', 'equipamento'),
  ('extintor', 'Extintores / combate a incendio', 'equipamento'),
  ('refrigeracao', 'Refrigeracao', 'equipamento'),
  ('controle de pragas', 'Controle de pragas / dedetizacao', 'equipamento'),
  ('plataforma de acessibilidade', 'Portas automaticas / sensores', 'equipamento'),
  ('monta cargas', 'Elevadores / escadas rolantes', 'equipamento'),
  ('poco artesiano', 'Hidraulica', 'equipamento'),
  ('balancas', 'Balancas / calibracao', 'assunto'),
  ('cftv', 'CFTV / seguranca patrimonial', 'assunto'),
  ('comunicacao visual', 'Comunicacao visual / fachada', 'assunto'),
  ('eletrica', 'Eletrica', 'assunto'),
  ('exaustao', 'Exaustao / ventilacao', 'assunto'),
  ('gas', 'Gas / GLP', 'assunto'),
  ('hidraulica', 'Hidraulica', 'assunto'),
  ('iluminacao', 'Iluminacao', 'assunto'),
  ('limpeza e conservacao', 'Limpeza e conservacao', 'assunto'),
  ('manutencao civil', 'Manutencao civil', 'assunto'),
  ('pintura', 'Pintura / reparos', 'assunto'),
  ('portas automaticas', 'Portas automaticas / sensores', 'assunto'),
  ('rede', 'Rede / TI / PDV', 'assunto'),
  ('residuos', 'Residuos / reciclagem', 'assunto'),
  ('sinalizacao', 'Sinalizacao / comunicacao interna', 'assunto'),
  ('termografia', 'Eletrica', 'assunto')
on conflict (termo) do nothing;

insert into public.taxonomia_sinonimos (termo_id, variacao, origem)
select t.id, v.variacao, 'semente'
from (values
  ('gerador', 'grupo gerador'),
  ('gerador', 'motogerador'),
  ('gerador', 'gmg'),
  ('gerador', 'alternador'),
  ('gerador', 'motor diesel'),
  ('gerador', 'teste de carga'),
  ('gerador', 'banco de carga'),
  ('gerador', 'nobreak'),
  ('gerador', 'ups'),
  ('gerador', 'ats'),
  ('gerador', 'transferencia automatica'),
  ('gerador', 'combustivel'),
  ('gerador', 'oleo diesel'),
  ('ar condicionado', 'climatizacao'),
  ('ar condicionado', 'split'),
  ('ar condicionado', 'fancoil'),
  ('ar condicionado', 'chiller'),
  ('ar condicionado', 'condensadora'),
  ('ar condicionado', 'evaporadora'),
  ('ar condicionado', 'gas refrigerante'),
  ('ar condicionado', 'compressor'),
  ('ar condicionado', 'dutos de ar'),
  ('ar condicionado', 'vrf'),
  ('ar condicionado', 'cassete'),
  ('elevador', 'casa de maquinas'),
  ('elevador', 'cabine do elevador'),
  ('elevador', 'botoeira'),
  ('elevador', 'cabo de tracao'),
  ('elevador', 'freio do elevador'),
  ('elevador', 'governador de velocidade'),
  ('elevador', 'poco do elevador'),
  ('escada rolante', 'esteira rolante'),
  ('escada rolante', 'degraus'),
  ('escada rolante', 'corrimao'),
  ('escada rolante', 'trilho'),
  ('subestacao', 'transformador'),
  ('subestacao', 'disjuntor'),
  ('subestacao', 'quadro de distribuicao'),
  ('subestacao', 'media tensao'),
  ('subestacao', 'baixa tensao'),
  ('subestacao', 'cabine primaria'),
  ('subestacao', 'para-raio'),
  ('subestacao', 'aterramento'),
  ('extintor', 'combate a incendio'),
  ('extintor', 'sistema de incendio'),
  ('extintor', 'hidrante'),
  ('extintor', 'mangueira de incendio'),
  ('extintor', 'sprinkler'),
  ('extintor', 'alarme de incendio'),
  ('extintor', 'deteccao de fumaca'),
  ('extintor', 'brigada de incendio'),
  ('extintor', 'recarga de extintor'),
  ('refrigeracao', 'camara fria'),
  ('refrigeracao', 'geladeira industrial'),
  ('refrigeracao', 'freezer'),
  ('refrigeracao', 'compressor de refrigeracao'),
  ('refrigeracao', 'unidade condensadora'),
  ('controle de pragas', 'dedetizacao'),
  ('controle de pragas', 'desratizacao'),
  ('controle de pragas', 'descupinizacao'),
  ('controle de pragas', 'praga urbana'),
  ('controle de pragas', 'inseticida'),
  ('plataforma de acessibilidade', 'plataforma elevatoria'),
  ('plataforma de acessibilidade', 'acessibilidade'),
  ('plataforma de acessibilidade', 'cadeirante'),
  ('monta cargas', 'montacargas'),
  ('monta cargas', 'elevador de carga'),
  ('poco artesiano', 'poco semi-artesiano'),
  ('poco artesiano', 'captacao de agua'),
  ('poco artesiano', 'bomba submersa'),
  ('balancas', 'calibracao'),
  ('balancas', 'afericao'),
  ('balancas', 'pesagem'),
  ('cftv', 'camera de seguranca'),
  ('cftv', 'monitoramento'),
  ('cftv', 'seguranca patrimonial'),
  ('cftv', 'alarme'),
  ('comunicacao visual', 'fachada'),
  ('comunicacao visual', 'letreiro'),
  ('comunicacao visual', 'placa'),
  ('comunicacao visual', 'banner'),
  ('eletrica', 'instalacao eletrica'),
  ('eletrica', 'quadro eletrico'),
  ('eletrica', 'disjuntores'),
  ('eletrica', 'fiacao'),
  ('eletrica', 'curto-circuito'),
  ('exaustao', 'ventilacao'),
  ('exaustao', 'coifa'),
  ('exaustao', 'dutos de exaustao'),
  ('exaustao', 'exaustor'),
  ('gas', 'glp'),
  ('gas', 'botijao'),
  ('gas', 'tubulacao de gas'),
  ('gas', 'vazamento de gas'),
  ('hidraulica', 'encanamento'),
  ('hidraulica', 'vazamento'),
  ('hidraulica', 'tubulacao'),
  ('hidraulica', 'caixa dagua'),
  ('hidraulica', 'bomba dagua'),
  ('iluminacao', 'lampada'),
  ('iluminacao', 'luminaria'),
  ('iluminacao', 'refletor'),
  ('iluminacao', 'sensor de presenca'),
  ('limpeza e conservacao', 'conservacao'),
  ('limpeza e conservacao', 'faxina'),
  ('limpeza e conservacao', 'higienizacao'),
  ('manutencao civil', 'reforma'),
  ('manutencao civil', 'alvenaria'),
  ('manutencao civil', 'reparo estrutural'),
  ('manutencao civil', 'infiltracao'),
  ('pintura', 'reparo'),
  ('pintura', 'retoque'),
  ('pintura', 'repintura'),
  ('portas automaticas', 'catraca'),
  ('portas automaticas', 'roleta'),
  ('portas automaticas', 'portao automatico'),
  ('rede', 'ti'),
  ('rede', 'pdv'),
  ('rede', 'cabeamento'),
  ('rede', 'roteador'),
  ('rede', 'switch'),
  ('rede', 'ponto de venda'),
  ('residuos', 'reciclagem'),
  ('residuos', 'coleta seletiva'),
  ('residuos', 'descarte'),
  ('sinalizacao', 'comunicacao interna'),
  ('sinalizacao', 'placa de sinalizacao'),
  ('termografia', 'inspecao termografica'),
  ('termografia', 'camera termica'),
  ('termografia', 'termovisao')
) as v(termo, variacao)
join public.taxonomia_termos t on t.termo = v.termo
on conflict (variacao) do nothing;
